{{- if .Values.inferenceService.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.inferenceService.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ml-model.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- if .Values.trainingJob.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.trainingJob.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ml-model.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
