{{- if .Values.inferenceService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.inferenceService.serviceAccountName }}
  namespace: {{ .Values.inferenceService.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ml-model.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.inferenceService.iamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.inferenceService.iamRoleArn }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
